---
# tasks file for role-cte_agent

- name: Retrieve all tags on an instance
  amazon.aws.ec2_tag_info:
    region: us-east-1
    resource: i-05d3c2f715fccc145
  register: ec2_tags

- name: Retrieve all tags on an instance
  amazon.aws.ec2_metadata_facts:
  register: ec2_instance

  #- name: debug
  #  debug:
  #    msg: "{{ansible_facts}}"
  #  
  #- name: Print ec2_tags variable
  #  debug:
  #    var: ec2_tags
  #
- set_fact: 
    ensure: 'present'
  #when: (ec2_tags.tags.CipherTrustManagement) and ((ec2_tags.tags.CipherTrustManagement |lower)  == 'true')
  when: (ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement |lower)  == 'present')

- set_fact: 
    ensure: 'absent'
  when: (ec2_tags.tags.CipherTrustManagement is not defined) or ((ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present'))
  #- not ec2_tags.tags.CipherTrustManagement
  #- (ec2_tags.tags.CipherTrustManagement) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present')
  #- (ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present')

- block: 
  - block: 
    - name: copy CTEintallAnswer.conf using jinja
      template: 
        owner: root
        group: root
        mode: '0644'
        src: "CTEinstallAnswer.conf.jinja"
        dest: "{{ answer_file }}"

        #    - name: Download CTE agent
        #      get_url:
        #        url: "{{ cte_source }}/vee-fs-7.1.1-71-rh8-x86_64.bin"
        #        dest: "{{ scratch_dir }}/vee-fs-7.1.1-71-rh8-x86_64.bin"
        #        owner: root
        #        group: root
        #        mode: '0755'
        #
        #    - name: Check vmsec available
        #      stat: 
        #        path: /bin/vmsec
        #      register: vmsec_bin
        #  
        #    - name: Install CTE agent
        #      command: "{{ scratch_dir }}/vee-fs-7.1.1-71-rh8-x86_64.bin -s {{ answer_file }} -t {{ scratch_dir }}"
        #      when: not vmsec_bin.stat.exists

    when: ensure == 'present'
  when: ansible_system == "Linux"

- debug: 
    msg: "CTE Agent is not yet supported on this platform on {{ inventory_hostname }}" 
  when: ansible_system != "Linux" and ansible_system != "Windows"
