---
# tasks file for role-cte_agent

- name: Retrieve all information about the instance
  amazon.aws.ec2_metadata_facts:
  register: ec2_instance

- name: Print ec2_instance variable
  debug:
    var: ec2_instance

- name: Retrieve all tags on an instance
  amazon.aws.ec2_tag_info:
    #region: us-east-1
    region: "{{ ec2_instance.ansible_facts.ansible_ec2_placement_region }}"
    #resource: i-05d3c2f715fccc145
    resource: "{{ ec2_instance.ansible_facts.ansible_ec2_instance_id }}"
  register: ec2_tags

- name: Print ec2_tags variable
  debug:
    var: ec2_tags

- set_fact: 
    ensure: 'present'
  #when: (ec2_tags.tags.CipherTrustManagement) and ((ec2_tags.tags.CipherTrustManagement |lower)  == 'true')
  when: (ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement |lower)  == 'present')

- set_fact: 
    ensure: 'absent'
  when: (ec2_tags.tags.CipherTrustManagement is not defined) or ((ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present'))
  #- not ec2_tags.tags.CipherTrustManagement
  #- (ec2_tags.tags.CipherTrustManagement) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present')
  #- (ec2_tags.tags.CipherTrustManagement is defined) and ((ec2_tags.tags.CipherTrustManagement|lower) != 'present')

- block: 
  - block: 
    - name: copy CTEintallAnswer.conf using jinja
      template: 
        owner: root
        group: root
        mode: '0644'
        #src: "CTEinstallAnswer.conf.j2"
        src: "/home/shyam/linux-base-test-node/playbook-linux-base/roles/role-cte_agent/templates/CTEinstallAnswer.conf.j2"
        dest: "{{ answer_file }}"

    - name: Download CTE agent
      get_url:
        url: "{{ cte_source }}/vee-fs-7.1.1-71-rh8-x86_64.bin"
        #dest: "{{ scratch_dir }}/vee-fs-7.1.1-71-rh8-x86_64.bin"
        dest: /tmp/vee-fs-7.1.1-71-rh8-x86_64.bin
        owner: root
        group: root
        mode: '0755'

    - name: Install dependency for vee-fs
      yum: 
        name: httpd
        state: installed
        update_cache: yes

    - name: Check vmsec available
      stat: 
        path: /bin/vmsec
      register: vmsec_bin
  
    - name: Install CTE agent
      #command: "{{ scratch_dir }}/vee-fs-7.1.1-71-rh8-x86_64.bin -s {{ answer_file }} -t {{ scratch_dir }}"
      command: "/tmp/vee-fs-7.1.1-71-rh8-x86_64.bin -s {{ answer_file }} -t /tmp"
      when: not vmsec_bin.stat.exists

    when: ensure == 'present'
  when: ansible_system == "Linux"

- debug: 
    msg: "CTE Agent is not yet supported on this platform on {{ inventory_hostname }}" 
  when: ansible_system != "Linux" and ansible_system != "Windows"
